spring:
  datasource:
    url: jdbc:mysql://dmxiaoshen.mysql.com:5506/spring_boot_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dmxiaoshen
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/*Dao.xml

pagehelper:
  reasonable: true
  helper-dialect: mysql